version: '2'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    hostname: localhost
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - pg:/var/lib/postgresql/data
  redis:
    image: redis
  node:
    container_name: node
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  pg: